---
title: "141a final"
author: "Xinhui Luo"
date: "2022-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ISLR)
library("corrplot")
data("College")
summary(College$Grad.Rate)
```

full model
```{r}
fmodel = lm(Grad.Rate~ ., data = College)
summary(fmodel)
```

subset of the variables
```{r}
College.sub <- College[,c(4, 5, 6, 7, 8, 15, 17)]
```

Corration plot
```{r}
corrplot(cor(College.sub), method = "number")
```

Remove and replace variables
```{r}
College.new <- College[,c(4, 6, 8, 9, 10, 15, 17)]
```

Performe linear regression model
```{r}
model1 = lm(College$Grad.Rate ~ ., data = College.new)
summary(model1)
par(mfrow=c(2,2))
plot(model1)
```

Remove outlier
```{r}
College_red = College.new[abs(rstandard(model1)) <= 3,]
Grad_red = College$Grad.Rate[abs(rstandard(model1)) <= 3]
```

no sf ratio
```{r}
College_o = lm(Grad_red ~ Enroll+Top25perc+P.Undergrad+Outstate+Room.Board+Expend, data = College_red)
summary(College_o)
par(mfrow=c(2,2))
plot(College_all)
```
##########part 2
pca
```{r}
College_pca <- College[,c(4, 5, 6, 7, 8, 15, 17, 18)]

hca <- prcomp(College_pca, scale. = TRUE)

summary(hca$rotation)

College_scale <- scale(College_pca)
hc = hclust(dist(College_scale), method = "complete")
plot(hc, cex = 0.75, hang = -1)
cut10 = cutree(hc, k = 10)
plot(cut10)
```

